batch_shuffle: false
batch_size: 8
buckeye_path: /data/felix/datasets/buckeye_processed_by_speaker_balanced
buckeye_percent: 1.0
ckpt: null
cosine_coef: 1.0
data: timit
dataloader_n_workers: 10
dev_run: false
early_stop_metric: val_max_rval
early_stop_mode: max
epochs: 200
exp_name: default
gpus: 1
grad_clip: 0.5
host: bryce-ubuntu
latent_dim: 0
libri_path: /data/felix/datasets/librispeech
libri_percent: 1.0
libri_subset: train-clean-100
lr: 0.0002
lr_anneal_gamma: 1.0
lr_anneal_step: 1000
momentum: 0.9
n_negatives: 1
optimizer: adam
overfit_pct: 1
pred_offset: 0
pred_steps: 1
project: unsupervised_segmentor
seed: 100
tag: default
timit_path: /home/bryce/PycharmProjects/UnsupSeg38/timit_restructured
val_check_interval: 0.2
val_ratio: 0.1
wd: /home/bryce/PycharmProjects/UnsupSeg38/runs/2021-09-08_13-39-55-default
z_dim: 256
z_proj: 64
z_proj_dropout: 0
z_proj_linear: true
